const carData = [
    {
        "brand": "Renault",
        "model": "Fluence",
        "year": 2015,
        "engine_name": "1.5 dCi",
        "hp": 105,
        "torque": 240,
        "fuel": "Dizel",
        "acc": 11.0,
        "top_speed": 185,
        "cons": 4.5,
        "weight": 1280,
        "baggage": 530,
        "image": "img/renault_fluence.jpg",
        "score": 77,
        "s_fuel": 93,
        "s_hp": 61,
        "s_comfort": 72,
        "s_tech": 77
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2007,
        "engine_name": "1.4 D-4D",
        "hp": 90,
        "torque": 190,
        "fuel": "Dizel",
        "acc": 12.0,
        "top_speed": 175,
        "cons": 4.9,
        "weight": 1270,
        "baggage": 450,
        "image": "img/toyota_corolla.jpg",
        "score": 64,
        "s_fuel": 88,
        "s_hp": 46,
        "s_comfort": 60,
        "s_tech": 57
    },
    {
        "brand": "Fiat",
        "model": "Linea",
        "year": 2012,
        "engine_name": "1.6 Multijet",
        "hp": 105,
        "torque": 290,
        "fuel": "Dizel",
        "acc": 11.0,
        "top_speed": 190,
        "cons": 5.1,
        "weight": 1250,
        "baggage": 500,
        "image": "img/fiat_linea.jpg",
        "score": 73,
        "s_fuel": 86,
        "s_hp": 66,
        "s_comfort": 68,
        "s_tech": 70
    },
    {
        "brand": "Honda",
        "model": "Civic",
        "year": 2021,
        "engine_name": "1.5 VTEC Turbo",
        "hp": 182,
        "torque": 220,
        "fuel": "Benzin",
        "acc": 8.1,
        "top_speed": 210,
        "cons": 6.0,
        "weight": 1350,
        "baggage": 519,
        "image": "img/honda_civic.jpg",
        "score": 82,
        "s_fuel": 75,
        "s_hp": 83,
        "s_comfort": 81,
        "s_tech": 92
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2017,
        "engine_name": "1.6 Multijet II",
        "hp": 120,
        "torque": 320,
        "fuel": "Dizel",
        "acc": 9.8,
        "top_speed": 200,
        "cons": 4.5,
        "weight": 1300,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 83,
        "s_fuel": 93,
        "s_hp": 80,
        "s_comfort": 75,
        "s_tech": 82
    },
    {
        "brand": "Honda",
        "model": "Civic",
        "year": 2016,
        "engine_name": "1.6 i-VTEC Eco",
        "hp": 125,
        "torque": 152,
        "fuel": "Benzin/LPG",
        "acc": 10.5,
        "top_speed": 198,
        "cons": 7.0,
        "weight": 1240,
        "baggage": 440,
        "image": "img/honda_civic.jpg",
        "score": 67,
        "s_fuel": 62,
        "s_hp": 55,
        "s_comfort": 74,
        "s_tech": 80
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2011,
        "engine_name": "1.6 TDI BlueMotion",
        "hp": 105,
        "torque": 250,
        "fuel": "Dizel",
        "acc": 12.2,
        "top_speed": 195,
        "cons": 4.3,
        "weight": 1490,
        "baggage": 565,
        "image": "img/volkswagen_passat.jpg",
        "score": 74,
        "s_fuel": 96,
        "s_hp": 52,
        "s_comfort": 76,
        "s_tech": 67
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2025,
        "engine_name": "1.5 Hibrit",
        "hp": 130,
        "torque": 240,
        "fuel": "Hibrit",
        "acc": 9.0,
        "top_speed": 205,
        "cons": 4.9,
        "weight": 1350,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 88,
        "s_fuel": 88,
        "s_hp": 77,
        "s_comfort": 87,
        "s_tech": 100
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2015,
        "engine_name": "1.5 TSI",
        "hp": 150,
        "torque": 250,
        "fuel": "Benzin",
        "acc": 8.7,
        "top_speed": 220,
        "cons": 5.3,
        "weight": 1420,
        "baggage": 586,
        "image": "img/volkswagen_passat.jpg",
        "score": 81,
        "s_fuel": 83,
        "s_hp": 81,
        "s_comfort": 82,
        "s_tech": 77
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2006,
        "engine_name": "1.5 dCi",
        "hp": 80,
        "torque": 185,
        "fuel": "Dizel",
        "acc": 14.3,
        "top_speed": 170,
        "cons": 4.6,
        "weight": 1205,
        "baggage": 520,
        "image": "img/renault_megane.jpg",
        "score": 63,
        "s_fuel": 92,
        "s_hp": 39,
        "s_comfort": 59,
        "s_tech": 55
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2023,
        "engine_name": "1.5 Vision",
        "hp": 123,
        "torque": 153,
        "fuel": "Benzin",
        "acc": 12.1,
        "top_speed": 190,
        "cons": 5.8,
        "weight": 1290,
        "baggage": 471,
        "image": "img/toyota_corolla.jpg",
        "score": 74,
        "s_fuel": 77,
        "s_hp": 41,
        "s_comfort": 84,
        "s_tech": 97
    },
    {
        "brand": "Honda",
        "model": "Civic",
        "year": 2008,
        "engine_name": "1.6 i-VTEC",
        "hp": 125,
        "torque": 152,
        "fuel": "Benzin",
        "acc": 10.3,
        "top_speed": 200,
        "cons": 7.5,
        "weight": 1190,
        "baggage": 389,
        "image": "img/honda_civic.jpg",
        "score": 58,
        "s_fuel": 56,
        "s_hp": 56,
        "s_comfort": 62,
        "s_tech": 60
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2014,
        "engine_name": "1.5 dCi EDC",
        "hp": 110,
        "torque": 240,
        "fuel": "Dizel",
        "acc": 11.9,
        "top_speed": 190,
        "cons": 4.4,
        "weight": 1290,
        "baggage": 405,
        "image": "img/renault_megane.jpg",
        "score": 74,
        "s_fuel": 95,
        "s_hp": 53,
        "s_comfort": 71,
        "s_tech": 75
    },
    {
        "brand": "Honda",
        "model": "Civic",
        "year": 2014,
        "engine_name": "1.6 i-VTEC Eco",
        "hp": 125,
        "torque": 152,
        "fuel": "Benzin/LPG",
        "acc": 10.5,
        "top_speed": 198,
        "cons": 7.0,
        "weight": 1240,
        "baggage": 440,
        "image": "img/honda_civic.jpg",
        "score": 65,
        "s_fuel": 62,
        "s_hp": 55,
        "s_comfort": 71,
        "s_tech": 75
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2010,
        "engine_name": "1.5 dCi EDC",
        "hp": 110,
        "torque": 240,
        "fuel": "Dizel",
        "acc": 11.9,
        "top_speed": 190,
        "cons": 4.4,
        "weight": 1290,
        "baggage": 405,
        "image": "img/renault_megane.jpg",
        "score": 71,
        "s_fuel": 95,
        "s_hp": 53,
        "s_comfort": 65,
        "s_tech": 65
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2019,
        "engine_name": "1.8 Hybrid Dream",
        "hp": 122,
        "torque": 142,
        "fuel": "Hibrit",
        "acc": 11.0,
        "top_speed": 180,
        "cons": 3.8,
        "weight": 1380,
        "baggage": 471,
        "image": "img/toyota_corolla.jpg",
        "score": 80,
        "s_fuel": 100,
        "s_hp": 49,
        "s_comfort": 78,
        "s_tech": 87
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2022,
        "engine_name": "1.5 dCi",
        "hp": 110,
        "torque": 260,
        "fuel": "Dizel",
        "acc": 11.2,
        "top_speed": 190,
        "cons": 3.9,
        "weight": 1380,
        "baggage": 550,
        "image": "img/renault_megane.jpg",
        "score": 85,
        "s_fuel": 100,
        "s_hp": 61,
        "s_comfort": 83,
        "s_tech": 95
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2013,
        "engine_name": "1.6 Valvematic",
        "hp": 132,
        "torque": 160,
        "fuel": "Benzin",
        "acc": 10.0,
        "top_speed": 200,
        "cons": 6.0,
        "weight": 1260,
        "baggage": 452,
        "image": "img/toyota_corolla.jpg",
        "score": 69,
        "s_fuel": 75,
        "s_hp": 60,
        "s_comfort": 69,
        "s_tech": 72
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2021,
        "engine_name": "1.8 Hybrid Dream",
        "hp": 122,
        "torque": 142,
        "fuel": "Hibrit",
        "acc": 11.0,
        "top_speed": 180,
        "cons": 3.8,
        "weight": 1380,
        "baggage": 471,
        "image": "img/toyota_corolla.jpg",
        "score": 82,
        "s_fuel": 100,
        "s_hp": 49,
        "s_comfort": 81,
        "s_tech": 92
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2013,
        "engine_name": "1.4 D-4D",
        "hp": 90,
        "torque": 205,
        "fuel": "Dizel",
        "acc": 12.5,
        "top_speed": 180,
        "cons": 4.1,
        "weight": 1280,
        "baggage": 452,
        "image": "img/toyota_corolla.jpg",
        "score": 72,
        "s_fuel": 98,
        "s_hp": 44,
        "s_comfort": 69,
        "s_tech": 72
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2007,
        "engine_name": "2.0 TDI",
        "hp": 140,
        "torque": 320,
        "fuel": "Dizel",
        "acc": 9.8,
        "top_speed": 209,
        "cons": 5.9,
        "weight": 1550,
        "baggage": 565,
        "image": "img/volkswagen_passat.jpg",
        "score": 72,
        "s_fuel": 76,
        "s_hp": 80,
        "s_comfort": 70,
        "s_tech": 57
    },
    {
        "brand": "Honda",
        "model": "Civic",
        "year": 2017,
        "engine_name": "1.5 VTEC Turbo",
        "hp": 182,
        "torque": 220,
        "fuel": "Benzin",
        "acc": 8.1,
        "top_speed": 210,
        "cons": 6.0,
        "weight": 1350,
        "baggage": 519,
        "image": "img/honda_civic.jpg",
        "score": 78,
        "s_fuel": 75,
        "s_hp": 83,
        "s_comfort": 75,
        "s_tech": 82
    },
    {
        "brand": "Honda",
        "model": "Civic",
        "year": 2012,
        "engine_name": "1.6 i-VTEC Eco",
        "hp": 125,
        "torque": 152,
        "fuel": "Benzin/LPG",
        "acc": 10.5,
        "top_speed": 198,
        "cons": 7.0,
        "weight": 1240,
        "baggage": 440,
        "image": "img/honda_civic.jpg",
        "score": 63,
        "s_fuel": 62,
        "s_hp": 55,
        "s_comfort": 68,
        "s_tech": 70
    },
    {
        "brand": "Renault",
        "model": "Fluence",
        "year": 2013,
        "engine_name": "1.5 dCi",
        "hp": 105,
        "torque": 240,
        "fuel": "Dizel",
        "acc": 11.0,
        "top_speed": 185,
        "cons": 4.5,
        "weight": 1280,
        "baggage": 530,
        "image": "img/renault_fluence.jpg",
        "score": 75,
        "s_fuel": 93,
        "s_hp": 61,
        "s_comfort": 69,
        "s_tech": 72
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2023,
        "engine_name": "1.0 FireFly",
        "hp": 100,
        "torque": 190,
        "fuel": "Benzin",
        "acc": 10.8,
        "top_speed": 192,
        "cons": 5.5,
        "weight": 1200,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 79,
        "s_fuel": 81,
        "s_hp": 56,
        "s_comfort": 84,
        "s_tech": 97
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2006,
        "engine_name": "1.6 16V",
        "hp": 115,
        "torque": 152,
        "fuel": "Benzin",
        "acc": 10.9,
        "top_speed": 192,
        "cons": 6.8,
        "weight": 1175,
        "baggage": 520,
        "image": "img/renault_megane.jpg",
        "score": 58,
        "s_fuel": 65,
        "s_hp": 51,
        "s_comfort": 59,
        "s_tech": 55
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2004,
        "engine_name": "1.6 16V",
        "hp": 115,
        "torque": 152,
        "fuel": "Benzin",
        "acc": 10.9,
        "top_speed": 192,
        "cons": 6.8,
        "weight": 1175,
        "baggage": 520,
        "image": "img/renault_megane.jpg",
        "score": 56,
        "s_fuel": 65,
        "s_hp": 51,
        "s_comfort": 56,
        "s_tech": 50
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2019,
        "engine_name": "1.3 Multijet II",
        "hp": 95,
        "torque": 200,
        "fuel": "Dizel",
        "acc": 11.7,
        "top_speed": 183,
        "cons": 4.1,
        "weight": 1270,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 79,
        "s_fuel": 98,
        "s_hp": 50,
        "s_comfort": 78,
        "s_tech": 87
    },
    {
        "brand": "Renault",
        "model": "Fluence",
        "year": 2011,
        "engine_name": "1.5 dCi EDC",
        "hp": 110,
        "torque": 240,
        "fuel": "Dizel",
        "acc": 11.9,
        "top_speed": 185,
        "cons": 4.4,
        "weight": 1290,
        "baggage": 530,
        "image": "img/renault_fluence.jpg",
        "score": 71,
        "s_fuel": 95,
        "s_hp": 53,
        "s_comfort": 66,
        "s_tech": 67
    },
    {
        "brand": "Fiat",
        "model": "Linea",
        "year": 2009,
        "engine_name": "1.3 Multijet",
        "hp": 90,
        "torque": 200,
        "fuel": "Dizel",
        "acc": 13.8,
        "top_speed": 170,
        "cons": 4.9,
        "weight": 1180,
        "baggage": 500,
        "image": "img/fiat_linea.jpg",
        "score": 65,
        "s_fuel": 88,
        "s_hp": 40,
        "s_comfort": 63,
        "s_tech": 62
    },
    {
        "brand": "Renault",
        "model": "Fluence",
        "year": 2009,
        "engine_name": "1.5 dCi",
        "hp": 105,
        "torque": 240,
        "fuel": "Dizel",
        "acc": 11.0,
        "top_speed": 185,
        "cons": 4.5,
        "weight": 1280,
        "baggage": 530,
        "image": "img/renault_fluence.jpg",
        "score": 71,
        "s_fuel": 93,
        "s_hp": 61,
        "s_comfort": 63,
        "s_tech": 62
    },
    {
        "brand": "Fiat",
        "model": "Linea",
        "year": 2014,
        "engine_name": "1.6 Multijet",
        "hp": 105,
        "torque": 290,
        "fuel": "Dizel",
        "acc": 11.0,
        "top_speed": 190,
        "cons": 5.1,
        "weight": 1250,
        "baggage": 500,
        "image": "img/fiat_linea.jpg",
        "score": 75,
        "s_fuel": 86,
        "s_hp": 66,
        "s_comfort": 71,
        "s_tech": 75
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2017,
        "engine_name": "1.6 TDI",
        "hp": 120,
        "torque": 250,
        "fuel": "Dizel",
        "acc": 10.8,
        "top_speed": 206,
        "cons": 4.1,
        "weight": 1480,
        "baggage": 586,
        "image": "img/volkswagen_passat.jpg",
        "score": 83,
        "s_fuel": 98,
        "s_hp": 63,
        "s_comfort": 85,
        "s_tech": 82
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2018,
        "engine_name": "1.5 dCi",
        "hp": 110,
        "torque": 260,
        "fuel": "Dizel",
        "acc": 11.2,
        "top_speed": 190,
        "cons": 3.9,
        "weight": 1380,
        "baggage": 550,
        "image": "img/renault_megane.jpg",
        "score": 82,
        "s_fuel": 100,
        "s_hp": 61,
        "s_comfort": 77,
        "s_tech": 85
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2007,
        "engine_name": "1.6 FSI",
        "hp": 115,
        "torque": 155,
        "fuel": "Benzin",
        "acc": 11.4,
        "top_speed": 200,
        "cons": 7.5,
        "weight": 1450,
        "baggage": 565,
        "image": "img/volkswagen_passat.jpg",
        "score": 57,
        "s_fuel": 56,
        "s_hp": 47,
        "s_comfort": 70,
        "s_tech": 57
    },
    {
        "brand": "Fiat",
        "model": "Linea",
        "year": 2012,
        "engine_name": "1.3 Multijet Euro5",
        "hp": 95,
        "torque": 200,
        "fuel": "Dizel",
        "acc": 13.8,
        "top_speed": 170,
        "cons": 4.9,
        "weight": 1185,
        "baggage": 500,
        "image": "img/fiat_linea.jpg",
        "score": 67,
        "s_fuel": 88,
        "s_hp": 40,
        "s_comfort": 68,
        "s_tech": 70
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2023,
        "engine_name": "1.6 TDI",
        "hp": 120,
        "torque": 250,
        "fuel": "Dizel",
        "acc": 10.8,
        "top_speed": 206,
        "cons": 4.1,
        "weight": 1480,
        "baggage": 586,
        "image": "img/volkswagen_passat.jpg",
        "score": 88,
        "s_fuel": 98,
        "s_hp": 63,
        "s_comfort": 94,
        "s_tech": 97
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2021,
        "engine_name": "1.5 Hibrit",
        "hp": 130,
        "torque": 240,
        "fuel": "Hibrit",
        "acc": 9.0,
        "top_speed": 205,
        "cons": 4.9,
        "weight": 1350,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 84,
        "s_fuel": 88,
        "s_hp": 77,
        "s_comfort": 81,
        "s_tech": 92
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2015,
        "engine_name": "1.6 Valvematic",
        "hp": 132,
        "torque": 160,
        "fuel": "Benzin",
        "acc": 10.0,
        "top_speed": 200,
        "cons": 6.0,
        "weight": 1260,
        "baggage": 452,
        "image": "img/toyota_corolla.jpg",
        "score": 71,
        "s_fuel": 75,
        "s_hp": 60,
        "s_comfort": 72,
        "s_tech": 77
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2011,
        "engine_name": "1.4 TSI",
        "hp": 122,
        "torque": 200,
        "fuel": "Benzin",
        "acc": 10.3,
        "top_speed": 205,
        "cons": 6.3,
        "weight": 1440,
        "baggage": 565,
        "image": "img/volkswagen_passat.jpg",
        "score": 69,
        "s_fuel": 71,
        "s_hp": 62,
        "s_comfort": 76,
        "s_tech": 67
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2019,
        "engine_name": "1.6 TDI",
        "hp": 120,
        "torque": 250,
        "fuel": "Dizel",
        "acc": 10.8,
        "top_speed": 206,
        "cons": 4.1,
        "weight": 1480,
        "baggage": 586,
        "image": "img/volkswagen_passat.jpg",
        "score": 85,
        "s_fuel": 98,
        "s_hp": 63,
        "s_comfort": 88,
        "s_tech": 87
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2025,
        "engine_name": "1.4 Fire",
        "hp": 95,
        "torque": 127,
        "fuel": "Benzin",
        "acc": 11.8,
        "top_speed": 186,
        "cons": 6.4,
        "weight": 1160,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 73,
        "s_fuel": 70,
        "s_hp": 41,
        "s_comfort": 87,
        "s_tech": 100
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2021,
        "engine_name": "1.5 Vision",
        "hp": 123,
        "torque": 153,
        "fuel": "Benzin",
        "acc": 12.1,
        "top_speed": 190,
        "cons": 5.8,
        "weight": 1290,
        "baggage": 471,
        "image": "img/toyota_corolla.jpg",
        "score": 72,
        "s_fuel": 77,
        "s_hp": 41,
        "s_comfort": 81,
        "s_tech": 92
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2015,
        "engine_name": "1.4 Fire",
        "hp": 95,
        "torque": 127,
        "fuel": "Benzin",
        "acc": 11.5,
        "top_speed": 185,
        "cons": 5.7,
        "weight": 1150,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 68,
        "s_fuel": 78,
        "s_hp": 43,
        "s_comfort": 72,
        "s_tech": 77
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2012,
        "engine_name": "1.5 dCi",
        "hp": 105,
        "torque": 240,
        "fuel": "Dizel",
        "acc": 10.9,
        "top_speed": 190,
        "cons": 4.5,
        "weight": 1280,
        "baggage": 405,
        "image": "img/renault_megane.jpg",
        "score": 74,
        "s_fuel": 93,
        "s_hp": 61,
        "s_comfort": 68,
        "s_tech": 70
    },
    {
        "brand": "Renault",
        "model": "Fluence",
        "year": 2009,
        "engine_name": "1.5 dCi EDC",
        "hp": 110,
        "torque": 240,
        "fuel": "Dizel",
        "acc": 11.9,
        "top_speed": 185,
        "cons": 4.4,
        "weight": 1290,
        "baggage": 530,
        "image": "img/renault_fluence.jpg",
        "score": 70,
        "s_fuel": 95,
        "s_hp": 53,
        "s_comfort": 63,
        "s_tech": 62
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2017,
        "engine_name": "1.4 D-4D",
        "hp": 90,
        "torque": 205,
        "fuel": "Dizel",
        "acc": 12.5,
        "top_speed": 180,
        "cons": 4.1,
        "weight": 1280,
        "baggage": 452,
        "image": "img/toyota_corolla.jpg",
        "score": 76,
        "s_fuel": 98,
        "s_hp": 44,
        "s_comfort": 75,
        "s_tech": 82
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2016,
        "engine_name": "1.5 dCi",
        "hp": 110,
        "torque": 260,
        "fuel": "Dizel",
        "acc": 11.2,
        "top_speed": 190,
        "cons": 3.9,
        "weight": 1380,
        "baggage": 550,
        "image": "img/renault_megane.jpg",
        "score": 80,
        "s_fuel": 100,
        "s_hp": 61,
        "s_comfort": 74,
        "s_tech": 80
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2021,
        "engine_name": "1.6 TDI",
        "hp": 120,
        "torque": 250,
        "fuel": "Dizel",
        "acc": 10.8,
        "top_speed": 206,
        "cons": 4.1,
        "weight": 1480,
        "baggage": 586,
        "image": "img/volkswagen_passat.jpg",
        "score": 86,
        "s_fuel": 98,
        "s_hp": 63,
        "s_comfort": 91,
        "s_tech": 92
    },
    {
        "brand": "Fiat",
        "model": "Linea",
        "year": 2016,
        "engine_name": "1.6 Multijet",
        "hp": 105,
        "torque": 290,
        "fuel": "Dizel",
        "acc": 11.0,
        "top_speed": 190,
        "cons": 5.1,
        "weight": 1250,
        "baggage": 500,
        "image": "img/fiat_linea.jpg",
        "score": 77,
        "s_fuel": 86,
        "s_hp": 66,
        "s_comfort": 74,
        "s_tech": 80
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2022,
        "engine_name": "1.3 TCe",
        "hp": 140,
        "torque": 240,
        "fuel": "Benzin",
        "acc": 9.0,
        "top_speed": 205,
        "cons": 5.5,
        "weight": 1350,
        "baggage": 550,
        "image": "img/renault_megane.jpg",
        "score": 83,
        "s_fuel": 81,
        "s_hp": 77,
        "s_comfort": 83,
        "s_tech": 95
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2004,
        "engine_name": "1.5 dCi",
        "hp": 80,
        "torque": 185,
        "fuel": "Dizel",
        "acc": 14.3,
        "top_speed": 170,
        "cons": 4.6,
        "weight": 1205,
        "baggage": 520,
        "image": "img/renault_megane.jpg",
        "score": 61,
        "s_fuel": 92,
        "s_hp": 39,
        "s_comfort": 56,
        "s_tech": 50
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2023,
        "engine_name": "1.5 TSI",
        "hp": 150,
        "torque": 250,
        "fuel": "Benzin",
        "acc": 8.7,
        "top_speed": 220,
        "cons": 5.3,
        "weight": 1420,
        "baggage": 586,
        "image": "img/volkswagen_passat.jpg",
        "score": 88,
        "s_fuel": 83,
        "s_hp": 81,
        "s_comfort": 94,
        "s_tech": 97
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2015,
        "engine_name": "1.6 Multijet II",
        "hp": 120,
        "torque": 320,
        "fuel": "Dizel",
        "acc": 9.8,
        "top_speed": 200,
        "cons": 4.5,
        "weight": 1300,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 81,
        "s_fuel": 93,
        "s_hp": 80,
        "s_comfort": 72,
        "s_tech": 77
    },
    {
        "brand": "Honda",
        "model": "Civic",
        "year": 2010,
        "engine_name": "1.6 i-VTEC",
        "hp": 125,
        "torque": 152,
        "fuel": "Benzin",
        "acc": 10.3,
        "top_speed": 200,
        "cons": 7.5,
        "weight": 1190,
        "baggage": 389,
        "image": "img/honda_civic.jpg",
        "score": 60,
        "s_fuel": 56,
        "s_hp": 56,
        "s_comfort": 65,
        "s_tech": 65
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2019,
        "engine_name": "1.6 Multijet II",
        "hp": 120,
        "torque": 320,
        "fuel": "Dizel",
        "acc": 9.8,
        "top_speed": 200,
        "cons": 4.5,
        "weight": 1300,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 85,
        "s_fuel": 93,
        "s_hp": 80,
        "s_comfort": 78,
        "s_tech": 87
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2009,
        "engine_name": "1.6 Dual VVT-i",
        "hp": 124,
        "torque": 157,
        "fuel": "Benzin",
        "acc": 10.4,
        "top_speed": 195,
        "cons": 6.9,
        "weight": 1250,
        "baggage": 450,
        "image": "img/toyota_corolla.jpg",
        "score": 61,
        "s_fuel": 63,
        "s_hp": 56,
        "s_comfort": 63,
        "s_tech": 62
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2013,
        "engine_name": "1.6 TDI BlueMotion",
        "hp": 105,
        "torque": 250,
        "fuel": "Dizel",
        "acc": 12.2,
        "top_speed": 195,
        "cons": 4.3,
        "weight": 1490,
        "baggage": 565,
        "image": "img/volkswagen_passat.jpg",
        "score": 76,
        "s_fuel": 96,
        "s_hp": 52,
        "s_comfort": 79,
        "s_tech": 72
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2017,
        "engine_name": "1.3 Multijet II",
        "hp": 95,
        "torque": 200,
        "fuel": "Dizel",
        "acc": 11.7,
        "top_speed": 183,
        "cons": 4.1,
        "weight": 1270,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 77,
        "s_fuel": 98,
        "s_hp": 50,
        "s_comfort": 75,
        "s_tech": 82
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2005,
        "engine_name": "1.6 FSI",
        "hp": 115,
        "torque": 155,
        "fuel": "Benzin",
        "acc": 11.4,
        "top_speed": 200,
        "cons": 7.5,
        "weight": 1450,
        "baggage": 565,
        "image": "img/volkswagen_passat.jpg",
        "score": 56,
        "s_fuel": 56,
        "s_hp": 47,
        "s_comfort": 67,
        "s_tech": 52
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2025,
        "engine_name": "1.5 Vision",
        "hp": 123,
        "torque": 153,
        "fuel": "Benzin",
        "acc": 12.1,
        "top_speed": 190,
        "cons": 5.8,
        "weight": 1290,
        "baggage": 471,
        "image": "img/toyota_corolla.jpg",
        "score": 76,
        "s_fuel": 77,
        "s_hp": 41,
        "s_comfort": 87,
        "s_tech": 100
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2011,
        "engine_name": "1.6 Dual VVT-i",
        "hp": 124,
        "torque": 157,
        "fuel": "Benzin",
        "acc": 10.4,
        "top_speed": 195,
        "cons": 6.9,
        "weight": 1250,
        "baggage": 450,
        "image": "img/toyota_corolla.jpg",
        "score": 63,
        "s_fuel": 63,
        "s_hp": 56,
        "s_comfort": 66,
        "s_tech": 67
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2025,
        "engine_name": "1.8 Hybrid Dream",
        "hp": 122,
        "torque": 142,
        "fuel": "Hibrit",
        "acc": 11.0,
        "top_speed": 180,
        "cons": 3.8,
        "weight": 1380,
        "baggage": 471,
        "image": "img/toyota_corolla.jpg",
        "score": 85,
        "s_fuel": 100,
        "s_hp": 49,
        "s_comfort": 87,
        "s_tech": 100
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2017,
        "engine_name": "1.5 TSI",
        "hp": 150,
        "torque": 250,
        "fuel": "Benzin",
        "acc": 8.7,
        "top_speed": 220,
        "cons": 5.3,
        "weight": 1420,
        "baggage": 586,
        "image": "img/volkswagen_passat.jpg",
        "score": 83,
        "s_fuel": 83,
        "s_hp": 81,
        "s_comfort": 85,
        "s_tech": 82
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2023,
        "engine_name": "1.8 Hybrid Dream",
        "hp": 122,
        "torque": 142,
        "fuel": "Hibrit",
        "acc": 11.0,
        "top_speed": 180,
        "cons": 3.8,
        "weight": 1380,
        "baggage": 471,
        "image": "img/toyota_corolla.jpg",
        "score": 83,
        "s_fuel": 100,
        "s_hp": 49,
        "s_comfort": 84,
        "s_tech": 97
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2025,
        "engine_name": "1.0 FireFly",
        "hp": 100,
        "torque": 190,
        "fuel": "Benzin",
        "acc": 10.8,
        "top_speed": 192,
        "cons": 5.5,
        "weight": 1200,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 80,
        "s_fuel": 81,
        "s_hp": 56,
        "s_comfort": 87,
        "s_tech": 100
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2019,
        "engine_name": "1.5 TSI",
        "hp": 150,
        "torque": 250,
        "fuel": "Benzin",
        "acc": 8.7,
        "top_speed": 220,
        "cons": 5.3,
        "weight": 1420,
        "baggage": 586,
        "image": "img/volkswagen_passat.jpg",
        "score": 85,
        "s_fuel": 83,
        "s_hp": 81,
        "s_comfort": 88,
        "s_tech": 87
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2021,
        "engine_name": "1.5 TSI",
        "hp": 150,
        "torque": 250,
        "fuel": "Benzin",
        "acc": 8.7,
        "top_speed": 220,
        "cons": 5.3,
        "weight": 1420,
        "baggage": 586,
        "image": "img/volkswagen_passat.jpg",
        "score": 86,
        "s_fuel": 83,
        "s_hp": 81,
        "s_comfort": 91,
        "s_tech": 92
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2008,
        "engine_name": "1.5 dCi",
        "hp": 80,
        "torque": 185,
        "fuel": "Dizel",
        "acc": 14.3,
        "top_speed": 170,
        "cons": 4.6,
        "weight": 1205,
        "baggage": 520,
        "image": "img/renault_megane.jpg",
        "score": 65,
        "s_fuel": 92,
        "s_hp": 39,
        "s_comfort": 62,
        "s_tech": 60
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2013,
        "engine_name": "1.4 TSI",
        "hp": 122,
        "torque": 200,
        "fuel": "Benzin",
        "acc": 10.3,
        "top_speed": 205,
        "cons": 6.3,
        "weight": 1440,
        "baggage": 565,
        "image": "img/volkswagen_passat.jpg",
        "score": 71,
        "s_fuel": 71,
        "s_hp": 62,
        "s_comfort": 79,
        "s_tech": 72
    },
    {
        "brand": "Renault",
        "model": "Fluence",
        "year": 2015,
        "engine_name": "1.5 dCi EDC",
        "hp": 110,
        "torque": 240,
        "fuel": "Dizel",
        "acc": 11.9,
        "top_speed": 185,
        "cons": 4.4,
        "weight": 1290,
        "baggage": 530,
        "image": "img/renault_fluence.jpg",
        "score": 75,
        "s_fuel": 95,
        "s_hp": 53,
        "s_comfort": 72,
        "s_tech": 77
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2019,
        "engine_name": "1.4 Fire",
        "hp": 95,
        "torque": 127,
        "fuel": "Benzin",
        "acc": 11.5,
        "top_speed": 185,
        "cons": 5.7,
        "weight": 1150,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 71,
        "s_fuel": 78,
        "s_hp": 43,
        "s_comfort": 78,
        "s_tech": 87
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2023,
        "engine_name": "1.4 Fire",
        "hp": 95,
        "torque": 127,
        "fuel": "Benzin",
        "acc": 11.8,
        "top_speed": 186,
        "cons": 6.4,
        "weight": 1160,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 71,
        "s_fuel": 70,
        "s_hp": 41,
        "s_comfort": 84,
        "s_tech": 97
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2017,
        "engine_name": "1.6 Valvematic",
        "hp": 132,
        "torque": 160,
        "fuel": "Benzin",
        "acc": 10.0,
        "top_speed": 200,
        "cons": 6.0,
        "weight": 1260,
        "baggage": 452,
        "image": "img/toyota_corolla.jpg",
        "score": 72,
        "s_fuel": 75,
        "s_hp": 60,
        "s_comfort": 75,
        "s_tech": 82
    },
    {
        "brand": "Honda",
        "model": "Civic",
        "year": 2019,
        "engine_name": "1.5 VTEC Turbo",
        "hp": 182,
        "torque": 220,
        "fuel": "Benzin",
        "acc": 8.1,
        "top_speed": 210,
        "cons": 6.0,
        "weight": 1350,
        "baggage": 519,
        "image": "img/honda_civic.jpg",
        "score": 80,
        "s_fuel": 75,
        "s_hp": 83,
        "s_comfort": 78,
        "s_tech": 87
    },
    {
        "brand": "Honda",
        "model": "Civic",
        "year": 2019,
        "engine_name": "1.6 i-VTEC",
        "hp": 125,
        "torque": 152,
        "fuel": "Benzin/LPG",
        "acc": 10.6,
        "top_speed": 200,
        "cons": 6.7,
        "weight": 1290,
        "baggage": 519,
        "image": "img/honda_civic.jpg",
        "score": 70,
        "s_fuel": 66,
        "s_hp": 54,
        "s_comfort": 78,
        "s_tech": 87
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2014,
        "engine_name": "1.5 dCi",
        "hp": 105,
        "torque": 240,
        "fuel": "Dizel",
        "acc": 10.9,
        "top_speed": 190,
        "cons": 4.5,
        "weight": 1280,
        "baggage": 405,
        "image": "img/renault_megane.jpg",
        "score": 76,
        "s_fuel": 93,
        "s_hp": 61,
        "s_comfort": 71,
        "s_tech": 75
    },
    {
        "brand": "Fiat",
        "model": "Linea",
        "year": 2014,
        "engine_name": "1.3 Multijet Euro5",
        "hp": 95,
        "torque": 200,
        "fuel": "Dizel",
        "acc": 13.8,
        "top_speed": 170,
        "cons": 4.9,
        "weight": 1185,
        "baggage": 500,
        "image": "img/fiat_linea.jpg",
        "score": 69,
        "s_fuel": 88,
        "s_hp": 40,
        "s_comfort": 71,
        "s_tech": 75
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2024,
        "engine_name": "1.5 dCi",
        "hp": 110,
        "torque": 260,
        "fuel": "Dizel",
        "acc": 11.2,
        "top_speed": 190,
        "cons": 3.9,
        "weight": 1380,
        "baggage": 550,
        "image": "img/renault_megane.jpg",
        "score": 87,
        "s_fuel": 100,
        "s_hp": 61,
        "s_comfort": 86,
        "s_tech": 100
    },
    {
        "brand": "Fiat",
        "model": "Linea",
        "year": 2007,
        "engine_name": "1.3 Multijet",
        "hp": 90,
        "torque": 200,
        "fuel": "Dizel",
        "acc": 13.8,
        "top_speed": 170,
        "cons": 4.9,
        "weight": 1180,
        "baggage": 500,
        "image": "img/fiat_linea.jpg",
        "score": 63,
        "s_fuel": 88,
        "s_hp": 40,
        "s_comfort": 60,
        "s_tech": 57
    },
    {
        "brand": "Honda",
        "model": "Civic",
        "year": 2021,
        "engine_name": "1.6 i-VTEC",
        "hp": 125,
        "torque": 152,
        "fuel": "Benzin/LPG",
        "acc": 10.6,
        "top_speed": 200,
        "cons": 6.7,
        "weight": 1290,
        "baggage": 519,
        "image": "img/honda_civic.jpg",
        "score": 72,
        "s_fuel": 66,
        "s_hp": 54,
        "s_comfort": 81,
        "s_tech": 92
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2009,
        "engine_name": "2.0 TDI",
        "hp": 140,
        "torque": 320,
        "fuel": "Dizel",
        "acc": 9.8,
        "top_speed": 209,
        "cons": 5.9,
        "weight": 1550,
        "baggage": 565,
        "image": "img/volkswagen_passat.jpg",
        "score": 73,
        "s_fuel": 76,
        "s_hp": 80,
        "s_comfort": 73,
        "s_tech": 62
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2011,
        "engine_name": "1.4 D-4D",
        "hp": 90,
        "torque": 190,
        "fuel": "Dizel",
        "acc": 12.0,
        "top_speed": 175,
        "cons": 4.9,
        "weight": 1270,
        "baggage": 450,
        "image": "img/toyota_corolla.jpg",
        "score": 68,
        "s_fuel": 88,
        "s_hp": 46,
        "s_comfort": 66,
        "s_tech": 67
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2015,
        "engine_name": "1.3 Multijet II",
        "hp": 95,
        "torque": 200,
        "fuel": "Dizel",
        "acc": 11.7,
        "top_speed": 183,
        "cons": 4.1,
        "weight": 1270,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 75,
        "s_fuel": 98,
        "s_hp": 50,
        "s_comfort": 72,
        "s_tech": 77
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2019,
        "engine_name": "1.5 Vision",
        "hp": 123,
        "torque": 153,
        "fuel": "Benzin",
        "acc": 12.1,
        "top_speed": 190,
        "cons": 5.8,
        "weight": 1290,
        "baggage": 471,
        "image": "img/toyota_corolla.jpg",
        "score": 70,
        "s_fuel": 77,
        "s_hp": 41,
        "s_comfort": 78,
        "s_tech": 87
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2016,
        "engine_name": "1.3 TCe",
        "hp": 140,
        "torque": 240,
        "fuel": "Benzin",
        "acc": 9.0,
        "top_speed": 205,
        "cons": 5.5,
        "weight": 1350,
        "baggage": 550,
        "image": "img/renault_megane.jpg",
        "score": 78,
        "s_fuel": 81,
        "s_hp": 77,
        "s_comfort": 74,
        "s_tech": 80
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2012,
        "engine_name": "1.5 dCi EDC",
        "hp": 110,
        "torque": 240,
        "fuel": "Dizel",
        "acc": 11.9,
        "top_speed": 190,
        "cons": 4.4,
        "weight": 1290,
        "baggage": 405,
        "image": "img/renault_megane.jpg",
        "score": 72,
        "s_fuel": 95,
        "s_hp": 53,
        "s_comfort": 68,
        "s_tech": 70
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2017,
        "engine_name": "1.4 Fire",
        "hp": 95,
        "torque": 127,
        "fuel": "Benzin",
        "acc": 11.5,
        "top_speed": 185,
        "cons": 5.7,
        "weight": 1150,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 69,
        "s_fuel": 78,
        "s_hp": 43,
        "s_comfort": 75,
        "s_tech": 82
    },
    {
        "brand": "Renault",
        "model": "Fluence",
        "year": 2011,
        "engine_name": "1.5 dCi",
        "hp": 105,
        "torque": 240,
        "fuel": "Dizel",
        "acc": 11.0,
        "top_speed": 185,
        "cons": 4.5,
        "weight": 1280,
        "baggage": 530,
        "image": "img/renault_fluence.jpg",
        "score": 73,
        "s_fuel": 93,
        "s_hp": 61,
        "s_comfort": 66,
        "s_tech": 67
    },
    {
        "brand": "Fiat",
        "model": "Linea",
        "year": 2011,
        "engine_name": "1.3 Multijet",
        "hp": 90,
        "torque": 200,
        "fuel": "Dizel",
        "acc": 13.8,
        "top_speed": 170,
        "cons": 4.9,
        "weight": 1180,
        "baggage": 500,
        "image": "img/fiat_linea.jpg",
        "score": 66,
        "s_fuel": 88,
        "s_hp": 40,
        "s_comfort": 66,
        "s_tech": 67
    },
    {
        "brand": "Honda",
        "model": "Civic",
        "year": 2006,
        "engine_name": "1.6 i-VTEC",
        "hp": 125,
        "torque": 152,
        "fuel": "Benzin",
        "acc": 10.3,
        "top_speed": 200,
        "cons": 7.5,
        "weight": 1190,
        "baggage": 389,
        "image": "img/honda_civic.jpg",
        "score": 56,
        "s_fuel": 56,
        "s_hp": 56,
        "s_comfort": 59,
        "s_tech": 55
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2015,
        "engine_name": "1.4 D-4D",
        "hp": 90,
        "torque": 205,
        "fuel": "Dizel",
        "acc": 12.5,
        "top_speed": 180,
        "cons": 4.1,
        "weight": 1280,
        "baggage": 452,
        "image": "img/toyota_corolla.jpg",
        "score": 74,
        "s_fuel": 98,
        "s_hp": 44,
        "s_comfort": 72,
        "s_tech": 77
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2021,
        "engine_name": "1.0 FireFly",
        "hp": 100,
        "torque": 190,
        "fuel": "Benzin",
        "acc": 10.8,
        "top_speed": 192,
        "cons": 5.5,
        "weight": 1200,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 77,
        "s_fuel": 81,
        "s_hp": 56,
        "s_comfort": 81,
        "s_tech": 92
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2018,
        "engine_name": "1.3 TCe",
        "hp": 140,
        "torque": 240,
        "fuel": "Benzin",
        "acc": 9.0,
        "top_speed": 205,
        "cons": 5.5,
        "weight": 1350,
        "baggage": 550,
        "image": "img/renault_megane.jpg",
        "score": 80,
        "s_fuel": 81,
        "s_hp": 77,
        "s_comfort": 77,
        "s_tech": 85
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2020,
        "engine_name": "1.3 TCe",
        "hp": 140,
        "torque": 240,
        "fuel": "Benzin",
        "acc": 9.0,
        "top_speed": 205,
        "cons": 5.5,
        "weight": 1350,
        "baggage": 550,
        "image": "img/renault_megane.jpg",
        "score": 81,
        "s_fuel": 81,
        "s_hp": 77,
        "s_comfort": 80,
        "s_tech": 90
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2005,
        "engine_name": "2.0 TDI",
        "hp": 140,
        "torque": 320,
        "fuel": "Dizel",
        "acc": 9.8,
        "top_speed": 209,
        "cons": 5.9,
        "weight": 1550,
        "baggage": 565,
        "image": "img/volkswagen_passat.jpg",
        "score": 70,
        "s_fuel": 76,
        "s_hp": 80,
        "s_comfort": 67,
        "s_tech": 52
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2015,
        "engine_name": "1.6 TDI",
        "hp": 120,
        "torque": 250,
        "fuel": "Dizel",
        "acc": 10.8,
        "top_speed": 206,
        "cons": 4.1,
        "weight": 1480,
        "baggage": 586,
        "image": "img/volkswagen_passat.jpg",
        "score": 81,
        "s_fuel": 98,
        "s_hp": 63,
        "s_comfort": 82,
        "s_tech": 77
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2023,
        "engine_name": "1.5 Hibrit",
        "hp": 130,
        "torque": 240,
        "fuel": "Hibrit",
        "acc": 9.0,
        "top_speed": 205,
        "cons": 4.9,
        "weight": 1350,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 86,
        "s_fuel": 88,
        "s_hp": 77,
        "s_comfort": 84,
        "s_tech": 97
    },
    {
        "brand": "Renault",
        "model": "Fluence",
        "year": 2013,
        "engine_name": "1.5 dCi EDC",
        "hp": 110,
        "torque": 240,
        "fuel": "Dizel",
        "acc": 11.9,
        "top_speed": 185,
        "cons": 4.4,
        "weight": 1290,
        "baggage": 530,
        "image": "img/renault_fluence.jpg",
        "score": 73,
        "s_fuel": 95,
        "s_hp": 53,
        "s_comfort": 69,
        "s_tech": 72
    },
    {
        "brand": "Fiat",
        "model": "Linea",
        "year": 2016,
        "engine_name": "1.3 Multijet Euro5",
        "hp": 95,
        "torque": 200,
        "fuel": "Dizel",
        "acc": 13.8,
        "top_speed": 170,
        "cons": 4.9,
        "weight": 1185,
        "baggage": 500,
        "image": "img/fiat_linea.jpg",
        "score": 71,
        "s_fuel": 88,
        "s_hp": 40,
        "s_comfort": 74,
        "s_tech": 80
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2007,
        "engine_name": "1.6 Dual VVT-i",
        "hp": 124,
        "torque": 157,
        "fuel": "Benzin",
        "acc": 10.4,
        "top_speed": 195,
        "cons": 6.9,
        "weight": 1250,
        "baggage": 450,
        "image": "img/toyota_corolla.jpg",
        "score": 59,
        "s_fuel": 63,
        "s_hp": 56,
        "s_comfort": 60,
        "s_tech": 57
    },
    {
        "brand": "Fiat",
        "model": "Egea",
        "year": 2021,
        "engine_name": "1.4 Fire",
        "hp": 95,
        "torque": 127,
        "fuel": "Benzin",
        "acc": 11.8,
        "top_speed": 186,
        "cons": 6.4,
        "weight": 1160,
        "baggage": 520,
        "image": "img/fiat_egea.jpg",
        "score": 70,
        "s_fuel": 70,
        "s_hp": 41,
        "s_comfort": 81,
        "s_tech": 92
    },
    {
        "brand": "Honda",
        "model": "Civic",
        "year": 2017,
        "engine_name": "1.6 i-VTEC",
        "hp": 125,
        "torque": 152,
        "fuel": "Benzin/LPG",
        "acc": 10.6,
        "top_speed": 200,
        "cons": 6.7,
        "weight": 1290,
        "baggage": 519,
        "image": "img/honda_civic.jpg",
        "score": 68,
        "s_fuel": 66,
        "s_hp": 54,
        "s_comfort": 75,
        "s_tech": 82
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2024,
        "engine_name": "1.3 TCe",
        "hp": 140,
        "torque": 240,
        "fuel": "Benzin",
        "acc": 9.0,
        "top_speed": 205,
        "cons": 5.5,
        "weight": 1350,
        "baggage": 550,
        "image": "img/renault_megane.jpg",
        "score": 85,
        "s_fuel": 81,
        "s_hp": 77,
        "s_comfort": 86,
        "s_tech": 100
    },
    {
        "brand": "Volkswagen",
        "model": "Passat",
        "year": 2009,
        "engine_name": "1.6 FSI",
        "hp": 115,
        "torque": 155,
        "fuel": "Benzin",
        "acc": 11.4,
        "top_speed": 200,
        "cons": 7.5,
        "weight": 1450,
        "baggage": 565,
        "image": "img/volkswagen_passat.jpg",
        "score": 59,
        "s_fuel": 56,
        "s_hp": 47,
        "s_comfort": 73,
        "s_tech": 62
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2020,
        "engine_name": "1.5 dCi",
        "hp": 110,
        "torque": 260,
        "fuel": "Dizel",
        "acc": 11.2,
        "top_speed": 190,
        "cons": 3.9,
        "weight": 1380,
        "baggage": 550,
        "image": "img/renault_megane.jpg",
        "score": 83,
        "s_fuel": 100,
        "s_hp": 61,
        "s_comfort": 80,
        "s_tech": 90
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2009,
        "engine_name": "1.4 D-4D",
        "hp": 90,
        "torque": 190,
        "fuel": "Dizel",
        "acc": 12.0,
        "top_speed": 175,
        "cons": 4.9,
        "weight": 1270,
        "baggage": 450,
        "image": "img/toyota_corolla.jpg",
        "score": 66,
        "s_fuel": 88,
        "s_hp": 46,
        "s_comfort": 63,
        "s_tech": 62
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2010,
        "engine_name": "1.5 dCi",
        "hp": 105,
        "torque": 240,
        "fuel": "Dizel",
        "acc": 10.9,
        "top_speed": 190,
        "cons": 4.5,
        "weight": 1280,
        "baggage": 405,
        "image": "img/renault_megane.jpg",
        "score": 72,
        "s_fuel": 93,
        "s_hp": 61,
        "s_comfort": 65,
        "s_tech": 65
    },
    {
        "brand": "Renault",
        "model": "Megane",
        "year": 2008,
        "engine_name": "1.6 16V",
        "hp": 115,
        "torque": 152,
        "fuel": "Benzin",
        "acc": 10.9,
        "top_speed": 192,
        "cons": 6.8,
        "weight": 1175,
        "baggage": 520,
        "image": "img/renault_megane.jpg",
        "score": 59,
        "s_fuel": 65,
        "s_hp": 51,
        "s_comfort": 62,
        "s_tech": 60
    }
];